#!/bin/sh
#
readline() {
  linetoread=$1
  file=$2
  sed $linetoread'q;d' $file
}

echo "Content-type: text/html"
echo ""

if ! [[ -f /etc/jffs2/webui.hash ]]; then
  salt=$RANDOM
  echo $salt'webui' | md5sum >/etc/jffs2/webui.hash
  echo $salt>>/etc/jffs2/webui.hash
fi

cat <<EOT
<!DOCTYPE html>
<html>
<head>
<title>Camera - WebUI</title>
<link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/styles.css">
</head>
<body>
<section>

<div class="card">
<form action="/cgi-bin/login_validate.sh">
<h2>Welcome</h2>
<input type="password" name="webuipassword" size=40><br><br>
Hint: default password is "webui"<br><br>
<input type="submit" class="button" value="Login"><br><br>
</form>
</div>
</section>

</body>
</html>
EOT
