#!/bin/sh

if [[ -f /etc/jffs2/www/index.html ]]; then
    source /etc/jffs2/www/cgi-bin/header
else
    source /mnt/anyka_hack/web_interface/www/cgi-bin/header
fi
if [[ -f /tmp/token.txt ]] && [[ "$token" == "$(readline 1 /tmp/token.txt)" ]]; then

#import settings
source /etc/jffs2/gergesettings.txt

if [[ "$command" == "reboot" ]]; then
  reboot
fi

date=`date`
ipadd=`ip route get 1 | awk '{print $NF;exit}'`
uptime=`uptime`
storage_info="<table style=\"margin: 0px auto\"><tr>"
table_string=$(df -h | head -n 1)
table_string="${table_string//Mounted on/Mounted_on}"
for i in $table_string; do
  storage_info="$storage_info<th>$i</th>"
done
storage_info="$storage_info</tr><tr>"
table_string=$(df -h | grep mtdblock6)
for i in $table_string; do
  storage_info="$storage_info<th>$i</th>"
done
storage_info="$storage_info</tr>"
table_string=$(df -h | grep mmcblk0)
if [[ ${#table_string} -gt 3 ]]; then
  storage_info="$storage_info<tr>"
  for i in $table_string; do
    storage_info="$storage_info<th>$i</th>"
  done
  storage_info="$storage_info</tr>"
fi
storage_info="$storage_info</table>"

cat <<EOT
<!DOCTYPE html>
<html>
<head>
<title>Camera - WebUI</title>
<link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/styles.css">
</head>
<body>
<div class="topnav">
  <a href="/cgi-bin/webui?token=$token">Home</a>
  <a href="/cgi-bin/settings?token=$token">Settings</a>
  <a class="active" href="/cgi-bin/system?token=$token">System</a>
  <a href="/cgi-bin/events?token=$token">Events</a>
  <a href="/cgi-bin/login">Exit</a>
</div>

<section>

<div class="card">
<h2>System</h2>
<button class="button" onclick="window.location.href='system?token=$token&command=reboot'">Reboot</button><br><br>
</div>

<div class="card">
<h2>Uptime</h2>
Date - $date
<br>
IP Address - $ipadd
<br>
Uptime - $uptime
<br>
<br>
</div>

<div class="card">
<h2>Storage</h2>
$storage_info
<br>
<br>
</div>

</section>
</body>
</html>
EOT

else
    if [[ -f /etc/jffs2/www/index.html ]]; then
        source /etc/jffs2/www/cgi-bin/footer
    else
        source /mnt/anyka_hack/web_interface/www/cgi-bin/footer
    fi
fi
